### ISSUE TITLE
作者请看看

### ISSUE THREAD

**Issue by xiaonian233** [gy12346123/BaiduCloudSupport#1]
作者我用这个软件一点登录软件就会停止运行
![image](https://cloud.githubusercontent.com/assets/21072615/22293154/77bb3794-e349-11e6-8866-51b2ee67f6b3.png)

**Comment by xiaonian233** [comment]
补充一下Windows8.1 64位

**Comment by gy12346123** [comment]
@xiaonian233 
1.确认下程序是否使用的是最新版本。
2.程序目录下文件是否完整。
3..NET环境需要4.6版本支持。如低于此版本请下载4.6版本安装后再运行本程序。

**Comment by xiaonian233** [comment]
![image](https://cloud.githubusercontent.com/assets/21072615/22319218/b8badc1e-e3bb-11e6-9698-ab35532a41b6.png)
作者下的是1.6新版，文件完整，.Net 4.6安装情况依旧
