### ISSUE TITLE
为什么没法用迅雷下载链接？

### ISSUE THREAD

**Issue by zkna** [gy12346123/BaiduCloudSupport#2]
为什么没法用迅雷下载链接？

**Comment by f-shake** [comment]
我的可以啊。。

**Comment by zkna** [comment]
哈哈，谢谢！！

**Comment by zkna** [comment]
在哪呢？

**Comment by f-shake** [comment]
把下载链接（在软件目录的download文件夹下）复制到迅雷的新建对话框里就行了啊，不行吗？

**Comment by zkna** [comment]
不行呀！！，迅雷解析不出来。。。
![qq 20170310170526](https://cloud.githubusercontent.com/assets/19741934/23788974/df746022-05b3-11e7-9348-ed917ece9860.png)

一直都是这个状态！！

**Comment by gy12346123** [comment]
迅雷识别下载链接可能有一些限制，比如过长等原因吧。。 我记得有一个功能可以在导出链接时生成短链，请尝试短链扔进迅雷后能否下载。

**Comment by zkna** [comment]
好的，我试试吧，只不过没有注释，很难看。。。。
